### ISSUE TITLE
Would prefer a wiki for Documentation

### ISSUE THREAD

**Issue by dlmather** [figure-io/polymer-matrix-diagram#1]
Boy, is that Readme long, my tired eyes would surely appreciated some kind of wiki that broke the information in more digestible chunks.

**Comment by kgryte** [comment]
@dlmather Thanks for the input. I agree: documenting APIs in a single README can be cumbersome and not optimal from a usability perspective. I will add a TODO item to explore different possibilities.

**Comment by kgryte** [comment]
@dlmather added a ToC to the README.

**Comment by dlmather** [comment]
Thanks! Much better.
